// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5Ee0LpYe5x6GIapk-cZ5QjK6cI9ysoMQ',
    appId: '1:647558652499:web:f4dcc166fcb7e8ee335ca6',
    messagingSenderId: '647558652499',
    projectId: 'chat-app-76c30',
    authDomain: 'chat-app-76c30.firebaseapp.com',
    storageBucket: 'chat-app-76c30.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmoPkKRvTtK2AhaSSLxKnGi6ixgWHbbg0',
    appId: '1:647558652499:android:b70666235602b680335ca6',
    messagingSenderId: '647558652499',
    projectId: 'chat-app-76c30',
    storageBucket: 'chat-app-76c30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2wJZ-XDMDxqXD7WqZkPjLE07J3YCMsT4',
    appId: '1:647558652499:ios:87a54c40ce366c73335ca6',
    messagingSenderId: '647558652499',
    projectId: 'chat-app-76c30',
    storageBucket: 'chat-app-76c30.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2wJZ-XDMDxqXD7WqZkPjLE07J3YCMsT4',
    appId: '1:647558652499:ios:a6a39d5b1c2c7cd4335ca6',
    messagingSenderId: '647558652499',
    projectId: 'chat-app-76c30',
    storageBucket: 'chat-app-76c30.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
